#!/usr/bin/env php
<?php

/**
 * ====================================================================
 * 
 * Seezoo-Framework
 * 
 * A simple MVC/action Framework on PHP 5.1.0 or newer
 * 
 * 
 * Command line bootstrap
 * 
 * @package  Seezoo-Framework
 * @author   Yoshiaki Sugimoto <neo.yoshiaki.sugimoto@gmail.com>
 * @license  MIT Licence
 * 
 * ====================================================================
 */

// Set command line flag 
define('SZ_COMMANDLINE_WORKER', 1);

// include bootstrap file
require_once(dirname(__FILE__) . '/seezoo.php'); 
