darwin: darwin_x64

darwin_x64:
	./scripts/build_darwin_x64.sh

darwin_x86:
	./scripts/build_darwin_x86.sh

linux: linux_x64

linux_x64:
	./scripts/build_linux_x64.sh

linux_x86:
	./scripts/build_linux_x64.sh

windows: windows_x64

windows_x64:
	./scripts/build_windows_x64.sh

windows_x86:
	./scripts/build_windows_x64.sh

